version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point

    working_directory: ~/Portfolio-OTA/portfolio # directory where steps will run

    docker: # run the steps with Docker
      - image: circleci/openjdk:11-stretch # ...with this image as the primary container; this is where all `steps` will run

    steps: # a collection of executable commands

      # check out source code to working directory
      - checkout:
          path: ~/Portfolio-OTA

      # - run: mvn dependency:go-offline # gets the project dependencies

      # - save_cache: # saves the project dependencies
      #     paths:
      #       - ~/.m2
      #     key: portfolio-{{ checksum "pom.xml" }}
      - run: mvn clean package # run the actual tests

      - run :
          name: Save test results
          command:
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit


      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples
